nelmio_cors:
  defaults:
    allow_origin: ["*"] # Adjust this to allow specific origins if needed
    allow_credentials: true
    allow_headers: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    expose_headers: []
    max_age: 3600

  paths:
    "^/api/":
      allow_origin: ["*"] # Adjust to allow specific origins for your API
      allow_headers: ["*"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      max_age: 3600
