security:
  password_hashers:
    Symfony\Component\Security\Core\User\InMemoryUser:
      algorithm: bcrypt

  providers:
    in_memory:
      memory:
        users:
          admin:
            password: "$2y$10$Wqp9ezzcekuZBlMfqXskq.SSxFOGJkDIacfv/yoeyNpBeNz9FhC.O" # bcrypt hashed "admin"
            roles: ["ROLE_ADMIN"]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        username_path: username
        password_path: password
      custom_authenticators:
        - App\Security\CustomAuthenticator

    api:
      pattern: ^/api
      stateless: true
      provider: in_memory
      custom_authenticators:
        - App\Security\CustomAuthenticator

  access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: ROLE_ADMIN }
